#This file was generated by "bin/rails generate model Threat name:string email:string severity:string"
class Threat < ApplicationRecord
  # Name restrictions.
  validates :name, uniqueness: false, length: {minimum: 2}
  # Email restrictions.
  validates :email, uniqueness: false, format: { with: URI::MailTo::EMAIL_REGEXP}
  # Severity Restriction
  validates :severity, inclusion: {in: Globals::ModelConstraints::Severities}

  def self.check?(name,content)
    return Threat.validate_name?(content) if name=="name"
    return Threat.validate_severity?(content) if name=="severity"
    return Threat.validate_email?(content) if name=="contact"
    false
  end
  def self.validate_email?(email)
    email =~ URI::MailTo::EMAIL_REGEXP
  end
  def self.validate_severity?(severity)
    Globals::ModelConstraints::Severities.include? severity
  end
  def self.validate_name?(name)
    name.length > 1
  end
end
